### PR TITLE
Essential (missing) touchevents added

### PR DESCRIPTION
**Pull request by graforlock**
- Added missing and absolutely essential touch events for mobile interactions as per issue [#558](https://github.com/choojs/choo/issues/558)

### CODE REVIEW

**Comment by bcomnes** [comment]
This is probably a fairly important fix.  Not 100% how events are handled though @yoshuawuyts you would have a better understanding of this.

**Comment by graforlock** [comment]
After doing this it still doesn't really fire them, which is weird. I put the issue in `choo` repo though.

**Comment by bcomnes** [comment]
Might be something in https://github.com/shama/bel as well.  Just a guess

**Comment by graforlock** [comment]
It looks as if it doesn't work in vanilla `bel` anyhow. I did raise an issue there.

**Comment by bcomnes** [comment]
Cool thank you, these are important to get working asap.

**Comment by bcomnes** [comment]
Just to keep this thread in sync, I tested bel for touch event support and found it working (at least partially) in iOS.  

I do believe these event names probably need to be added but I don't understand nanomorph enough to say definitely.

**Comment by bcomnes** [comment]
Perhaps we should also review https://developer.mozilla.org/en-US/docs/Web/Events for other events that might be missing as well.

**Pull request merged**
