### PR TITLE
Adds half of fix for nanocomponent #65

### PR DESCRIPTION
**Pull request by kristoferjoseph**
I need some help adding a test for this here.

### CODE REVIEW

**Comment by kristoferjoseph** [comment]
@bcomnes Looks like this patch interferes with onload being called. Are you seeing this as well?

**Comment by kristoferjoseph** [comment]
@yoshuawuyts you cool with me doing the update and publish dance?

**Comment by kristoferjoseph** [comment]
Am currently hunting down a case i  saw where replacing a child with a different child is causing unload to be called on the parent component.
Will try and make a test case, but seems like a nanocomponent issue.

**Comment by bcomnes** [comment]
This looks good, but we should be sure to explore nanocomponent failure modes before we release.

**Comment by bcomnes** [comment]
I'm thinking we cut a beta, and test it out with the ecosystem?

**Comment by bcomnes** [comment]
🎉`6.0.0-beta1`🎉

**Pull request merged**
